steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'CONTAINER_IMAGE_URL:$BUILD_ID'
      - '.' # Point to the webapp directory as the build context
    id: 'Build'

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'CONTAINER_IMAGE_URL:$BUILD_ID'
    id: 'Push'

  # 3. Deploy to GKE
  # First, get the credentials for the GKE cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'CLUSTER_NAME'
      - '--location'
      - 'CLUSTER_LOCATION'
      - '--project'
      - 'YOUR_PROJECT_ID'
    id: 'Get GKE Credentials'

  # Now, update the deployment to use the new image
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/webapp-deployment'
      - 'webapp=CONTAINER_IMAGE_URL:$BUILD_ID'
      - '--namespace'
      - 'webapp'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=CLUSTER_LOCATION'
      - 'CLOUDSDK_CONTAINER_CLUSTER=CLUSTER_NAME'
    id: 'Deploy to GKE'
